/* Generated By:JavaCC: Do not edit this line. SQLParserConstants.java */
package nts.ds.ds;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SQLParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int K_ALL = 5;
  /** RegularExpression Id. */
  int K_ALTER = 6;
  /** RegularExpression Id. */
  int K_AND = 7;
  /** RegularExpression Id. */
  int K_ANY = 8;
  /** RegularExpression Id. */
  int K_AS = 9;
  /** RegularExpression Id. */
  int K_ASC = 10;
  /** RegularExpression Id. */
  int K_BEGIN = 11;
  /** RegularExpression Id. */
  int K_BETWEEN = 12;
  /** RegularExpression Id. */
  int K_BINARY_INTEGER = 13;
  /** RegularExpression Id. */
  int K_BOOLEAN = 14;
  /** RegularExpression Id. */
  int K_BY = 15;
  /** RegularExpression Id. */
  int K_CALL = 16;
  /** RegularExpression Id. */
  int K_CASE = 17;
  /** RegularExpression Id. */
  int K_CAST = 18;
  /** RegularExpression Id. */
  int K_CHAR = 19;
  /** RegularExpression Id. */
  int K_CLOSE = 20;
  /** RegularExpression Id. */
  int K_COMMENT = 21;
  /** RegularExpression Id. */
  int K_COMMIT = 22;
  /** RegularExpression Id. */
  int K_COMMITTED = 23;
  /** RegularExpression Id. */
  int K_CONNECT = 24;
  /** RegularExpression Id. */
  int K_CONSTANT = 25;
  /** RegularExpression Id. */
  int K_CONSTRAINT = 26;
  /** RegularExpression Id. */
  int K_CONSTRAINTS = 27;
  /** RegularExpression Id. */
  int K_CURRENT = 28;
  /** RegularExpression Id. */
  int K_CURSOR = 29;
  /** RegularExpression Id. */
  int K_DATE = 30;
  /** RegularExpression Id. */
  int K_DECIMAL = 31;
  /** RegularExpression Id. */
  int K_DECLARE = 32;
  /** RegularExpression Id. */
  int K_DEFAULT = 33;
  /** RegularExpression Id. */
  int K_DELETE = 34;
  /** RegularExpression Id. */
  int K_DESC = 35;
  /** RegularExpression Id. */
  int K_DISTINCT = 36;
  /** RegularExpression Id. */
  int K_DO = 37;
  /** RegularExpression Id. */
  int K_ELSE = 38;
  /** RegularExpression Id. */
  int K_ELSIF = 39;
  /** RegularExpression Id. */
  int K_END = 40;
  /** RegularExpression Id. */
  int K_ESCAPE = 41;
  /** RegularExpression Id. */
  int K_EXCEPTION = 42;
  /** RegularExpression Id. */
  int K_EXCEPTION_INIT = 43;
  /** RegularExpression Id. */
  int K_EXCLUSIVE = 44;
  /** RegularExpression Id. */
  int K_EXISTS = 45;
  /** RegularExpression Id. */
  int K_EXIT = 46;
  /** RegularExpression Id. */
  int K_FETCH = 47;
  /** RegularExpression Id. */
  int K_FLOAT = 48;
  /** RegularExpression Id. */
  int K_FOR = 49;
  /** RegularExpression Id. */
  int K_FORALL = 50;
  /** RegularExpression Id. */
  int K_FROM = 51;
  /** RegularExpression Id. */
  int K_FULL = 52;
  /** RegularExpression Id. */
  int K_FUNCTION = 53;
  /** RegularExpression Id. */
  int K_GOTO = 54;
  /** RegularExpression Id. */
  int K_GROUP = 55;
  /** RegularExpression Id. */
  int K_HAVING = 56;
  /** RegularExpression Id. */
  int K_IF = 57;
  /** RegularExpression Id. */
  int K_IN = 58;
  /** RegularExpression Id. */
  int K_INDEX = 59;
  /** RegularExpression Id. */
  int K_INNER = 60;
  /** RegularExpression Id. */
  int K_INSERT = 61;
  /** RegularExpression Id. */
  int K_INTEGER = 62;
  /** RegularExpression Id. */
  int K_INTERSECT = 63;
  /** RegularExpression Id. */
  int K_INTO = 64;
  /** RegularExpression Id. */
  int K_IS = 65;
  /** RegularExpression Id. */
  int K_ISOLATION = 66;
  /** RegularExpression Id. */
  int K_LEFT = 67;
  /** RegularExpression Id. */
  int K_LIKE = 68;
  /** RegularExpression Id. */
  int K_LIMIT = 69;
  /** RegularExpression Id. */
  int K_LOCK = 70;
  /** RegularExpression Id. */
  int K_LOOP = 71;
  /** RegularExpression Id. */
  int K_MERGE = 72;
  /** RegularExpression Id. */
  int K_MINUS = 73;
  /** RegularExpression Id. */
  int K_NATURAL = 74;
  /** RegularExpression Id. */
  int K_NOT = 75;
  /** RegularExpression Id. */
  int K_NOWAIT = 76;
  /** RegularExpression Id. */
  int K_NULL = 77;
  /** RegularExpression Id. */
  int K_NULLS = 78;
  /** RegularExpression Id. */
  int K_NUMBER = 79;
  /** RegularExpression Id. */
  int K_OF = 80;
  /** RegularExpression Id. */
  int K_OFFSET = 81;
  /** RegularExpression Id. */
  int K_ON = 82;
  /** RegularExpression Id. */
  int K_ONLY = 83;
  /** RegularExpression Id. */
  int K_OPEN = 84;
  /** RegularExpression Id. */
  int K_OR = 85;
  /** RegularExpression Id. */
  int K_ORDER = 86;
  /** RegularExpression Id. */
  int K_OUT = 87;
  /** RegularExpression Id. */
  int K_OVER = 88;
  /** RegularExpression Id. */
  int K_PACKAGE = 89;
  /** RegularExpression Id. */
  int K_PARTITION = 90;
  /** RegularExpression Id. */
  int K_POSITIVE = 91;
  /** RegularExpression Id. */
  int K_PRAGMA = 92;
  /** RegularExpression Id. */
  int K_PRIOR = 93;
  /** RegularExpression Id. */
  int K_PROCEDURE = 94;
  /** RegularExpression Id. */
  int K_PX_GRANULE = 95;
  /** RegularExpression Id. */
  int K_RAISE = 96;
  /** RegularExpression Id. */
  int K_RANGE = 97;
  /** RegularExpression Id. */
  int K_READ = 98;
  /** RegularExpression Id. */
  int K_REAL = 99;
  /** RegularExpression Id. */
  int K_RECORD = 100;
  /** RegularExpression Id. */
  int K_REF = 101;
  /** RegularExpression Id. */
  int K_RETURN = 102;
  /** RegularExpression Id. */
  int K_RETURNING = 103;
  /** RegularExpression Id. */
  int K_REVERSE = 104;
  /** RegularExpression Id. */
  int K_RIGHT = 105;
  /** RegularExpression Id. */
  int K_ROLLBACK = 106;
  /** RegularExpression Id. */
  int K_ROW = 107;
  /** RegularExpression Id. */
  int K_ROWS = 108;
  /** RegularExpression Id. */
  int K_SAMPLE = 109;
  /** RegularExpression Id. */
  int K_SAVEPOINT = 110;
  /** RegularExpression Id. */
  int K_SELECT = 111;
  /** RegularExpression Id. */
  int K_SERIALIZABLE = 112;
  /** RegularExpression Id. */
  int K_SET = 113;
  /** RegularExpression Id. */
  int K_SHARE = 114;
  /** RegularExpression Id. */
  int K_SIBLINGS = 115;
  /** RegularExpression Id. */
  int K_SKIP = 116;
  /** RegularExpression Id. */
  int K_SMALLINT = 117;
  /** RegularExpression Id. */
  int K_SQL = 118;
  /** RegularExpression Id. */
  int K_START = 119;
  /** RegularExpression Id. */
  int K_TABLE = 120;
  /** RegularExpression Id. */
  int K_TEST = 121;
  /** RegularExpression Id. */
  int K_THEN = 122;
  /** RegularExpression Id. */
  int K_TO = 123;
  /** RegularExpression Id. */
  int K_TRANSACTION = 124;
  /** RegularExpression Id. */
  int K_UNION = 125;
  /** RegularExpression Id. */
  int K_UNIQUE = 126;
  /** RegularExpression Id. */
  int K_UPDATE = 127;
  /** RegularExpression Id. */
  int K_USE = 128;
  /** RegularExpression Id. */
  int K_USING = 129;
  /** RegularExpression Id. */
  int K_VALUES = 130;
  /** RegularExpression Id. */
  int K_VARCHAR2 = 131;
  /** RegularExpression Id. */
  int K_VARCHAR = 132;
  /** RegularExpression Id. */
  int K_WAIT = 133;
  /** RegularExpression Id. */
  int K_WHEN = 134;
  /** RegularExpression Id. */
  int K_WHERE = 135;
  /** RegularExpression Id. */
  int K_WHILE = 136;
  /** RegularExpression Id. */
  int K_WITH = 137;
  /** RegularExpression Id. */
  int K_WORK = 138;
  /** RegularExpression Id. */
  int K_WRITE = 139;
  /** RegularExpression Id. */
  int S_NUMBER = 140;
  /** RegularExpression Id. */
  int FLOAT = 141;
  /** RegularExpression Id. */
  int INTEGER = 142;
  /** RegularExpression Id. */
  int DIGIT = 143;
  /** RegularExpression Id. */
  int LINE_COMMENT = 144;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 145;
  /** RegularExpression Id. */
  int S_IDENTIFIER = 146;
  /** RegularExpression Id. */
  int LETTER = 147;
  /** RegularExpression Id. */
  int SPECIAL_CHARS = 148;
  /** RegularExpression Id. */
  int S_BIND = 149;
  /** RegularExpression Id. */
  int S_CHAR_LITERAL = 150;
  /** RegularExpression Id. */
  int S_QUOTED_IDENTIFIER = 151;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"ALL\"",
    "\"ALTER\"",
    "\"AND\"",
    "\"ANY\"",
    "\"AS\"",
    "\"ASC\"",
    "\"BEGIN\"",
    "\"BETWEEN\"",
    "\"BINARY_INTEGER\"",
    "\"BOOLEAN\"",
    "\"BY\"",
    "\"CALL\"",
    "\"CASE\"",
    "\"CAST\"",
    "\"CHAR\"",
    "\"CLOSE\"",
    "\"COMMENT\"",
    "\"COMMIT\"",
    "\"COMMITTED\"",
    "\"CONNECT\"",
    "\"CONSTANT\"",
    "\"CONSTRAINT\"",
    "\"CONSTRAINTS\"",
    "\"CURRENT\"",
    "\"CURSOR\"",
    "\"DATE\"",
    "\"DECIMAL\"",
    "\"DECLARE\"",
    "\"DEFAULT\"",
    "\"DELETE\"",
    "\"DESC\"",
    "\"DISTINCT\"",
    "\"DO\"",
    "\"ELSE\"",
    "\"ELSIF\"",
    "\"END\"",
    "\"ESCAPE\"",
    "\"EXCEPTION\"",
    "\"EXCEPTION_INIT\"",
    "\"EXCLUSIVE\"",
    "\"EXISTS\"",
    "\"EXIT\"",
    "\"FETCH\"",
    "\"FLOAT\"",
    "\"FOR\"",
    "\"FORALL\"",
    "\"FROM\"",
    "\"FULL\"",
    "\"FUNCTION\"",
    "\"GOTO\"",
    "\"GROUP\"",
    "\"HAVING\"",
    "\"IF\"",
    "\"IN\"",
    "\"INDEX\"",
    "\"INNER\"",
    "\"INSERT\"",
    "\"INTEGER\"",
    "\"INTERSECT\"",
    "\"INTO\"",
    "\"IS\"",
    "\"ISOLATION\"",
    "\"LEFT\"",
    "\"LIKE\"",
    "\"LIMIT\"",
    "\"LOCK\"",
    "\"LOOP\"",
    "\"MERGE\"",
    "\"MINUS\"",
    "\"NATURAL\"",
    "\"NOT\"",
    "\"NOWAIT\"",
    "\"NULL\"",
    "\"NULLS\"",
    "\"NUMBER\"",
    "\"OF\"",
    "\"OFFSET\"",
    "\"ON\"",
    "\"ONLY\"",
    "\"OPEN\"",
    "\"OR\"",
    "\"ORDER\"",
    "\"OUT\"",
    "\"OVER\"",
    "\"PACKAGE\"",
    "\"PARTITION\"",
    "\"POSITIVE\"",
    "\"PRAGMA\"",
    "\"PRIOR\"",
    "\"PROCEDURE\"",
    "\"PX_GRANULE\"",
    "\"RAISE\"",
    "\"RANGE\"",
    "\"READ\"",
    "\"REAL\"",
    "\"RECORD\"",
    "\"REF\"",
    "\"RETURN\"",
    "\"RETURNING\"",
    "\"REVERSE\"",
    "\"RIGHT\"",
    "\"ROLLBACK\"",
    "\"ROW\"",
    "\"ROWS\"",
    "\"SAMPLE\"",
    "\"SAVEPOINT\"",
    "\"SELECT\"",
    "\"SERIALIZABLE\"",
    "\"SET\"",
    "\"SHARE\"",
    "\"SIBLINGS\"",
    "\"SKIP\"",
    "\"SMALLINT\"",
    "\"SQL\"",
    "\"START\"",
    "\"TABLE\"",
    "\"TEST\"",
    "\"THEN\"",
    "\"TO\"",
    "\"TRANSACTION\"",
    "\"UNION\"",
    "\"UNIQUE\"",
    "\"UPDATE\"",
    "\"USE\"",
    "\"USING\"",
    "\"VALUES\"",
    "\"VARCHAR2\"",
    "\"VARCHAR\"",
    "\"WAIT\"",
    "\"WHEN\"",
    "\"WHERE\"",
    "\"WHILE\"",
    "\"WITH\"",
    "\"WORK\"",
    "\"WRITE\"",
    "<S_NUMBER>",
    "<FLOAT>",
    "<INTEGER>",
    "<DIGIT>",
    "<LINE_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "<S_IDENTIFIER>",
    "<LETTER>",
    "<SPECIAL_CHARS>",
    "<S_BIND>",
    "<S_CHAR_LITERAL>",
    "<S_QUOTED_IDENTIFIER>",
    "\";\"",
    "\".\"",
    "\"=\"",
    "\"!\"",
    "\"#\"",
    "\">\"",
    "\"<\"",
    "\"@\"",
    "\"(\"",
    "\")\"",
    "\"*\"",
    "\",\"",
    "\".*\"",
    "\"+\"",
    "\"-\"",
    "\"||\"",
    "\"/\"",
    "\"**\"",
    "\"=>\"",
  };

}
